#!/bin/sh

set -e

dotfiles=$1
if [ -z "$dotfiles" ]; then
    dotfiles=~/.dotfiles
fi

if [ ! -e $dotfiles ]; then
    git clone --recursive git://github.com/nullpuppy/dotfiles $dotfiles
fi
cd $dotfiles

$dotfiles/bin/dotfiles-install

mkdir -p $HOME/.local/share/{less,fasd}

# Make sure ~/.config and ~/.cache exist
mkdir ~/.config ~/.cache

